### ISSUE TITLE
Build project under proxy or offline

### ISSUE THREAD

**Issue by jcgueriaud** [devsoap/gradle-vaadin-flow#170]
Hello,

I would like to compile (with and without productionMode) vaadin project with this plugin.
I configured a nexus local repository to doynload all my dependencies.
It's working.

After that I tried: gradlew.bat jettyRun (on beverage-starter-flow-gradle project).
The build failed because nodejs cannot be found.
I tried to add a http proxy and nodejs is downloaded.

But after that I've got this error:
request to https://registry.npmjs.org/yarn failed, reason: connect ECONNREFUSED
...
npm ERR!
npm ERR! If you are behind a proxy, please make sure that the
npm ERR! 'proxy' config is set properly.  See: 'npm help config'

Is there a configuration like "ignoreMavenProxies" to "download all frontend tools using Maven proxy configurations" ?
Is it possible to download it manually and use local yarn/node tools (and dependencies) ? (or using nexus but I think that's not Nexus purpose)

Thanks

**Comment by johndevs** [comment]
Hi, 

You question contains a lot of use-cases so I'll go through them one-by-one.

**Offline Development mode**

In development mode if you do not have any client dependencies the project should work when you run Gradle with the ``--offline`` parameter. In that case Gradle will check your Gradle cache for previously downloaded dependencies and resolve to those. Since Vaadin uses WebJars for the frontend dependencies they should also be available in the Gradle cache.If you do have client dependencies the these needs to be downloaded into their own caches from NPM. See the next section for more info.

**Offline Production mode**

In production mode the frontend tooling needs to be downloaded from NPM so the plugin can compile the Javascript and bundle it. To do that it will use Yarn to download and manage the dependencies. The thing to note here is that, it not only need the actual frontend components, it also needs the tooling for compiling and bundling the dependencies. And that is not available via Maven so it needs to be downloaded from NPM. The plugin will download those automatically when online.

**Offline Caching**

To allow the plugin to work in spotty networks and mostly offline the plugin will set up a Yarn mirror and a Yarn cache when running the project the first time online. This cache and mirror will later be preferred when searching for dependencies and will allow you to work offline once you have got  all the dependencies in the cache. However, for it to work it requires you to run the project once online.

To enable offline development you will need to have the dependencies downloaded and cached. 
After that add **.gradle/yarn/yarn-offline-mirror** and **build/frontend/yarn.lock** to your version control. Then run the project with the ``--offline`` flag. This should work until you want to update your dependencies.

Unfortunately Yarn/Bower offline modes are not that good and have turned out to be really difficult to configure for every environment (if you search on google you'll find the issues). 

**HTTP/HTTPS proxy support for Yarn**

This is still missing, I'll add support for this for the next release.

**Comment by jcgueriaud** [comment]
Thanks a lot for your complete answer and your commits (so fast !).

I will search some solutions for offline yarn / npm. (a sort of "nexus" / "artifactory" for these tools)
