### ISSUE TITLE
Relative paths to templates

### ISSUE THREAD

**Issue by brp-oskar** [devsoap/gradle-vaadin-flow#173]
**Desktop (please complete the following information):**
 - OS: Windows
 - JDK version: 8
 - Gradle version: 5.0
 - Vaadin Plugin version: 1.0.0.RC4

**Describe the bug**
Task `:vaadinTranspileDependencies` fails with `Imported file 'C:\myproject\build\frontend\templates\..\components\my-component.html' in templates/views/my-view.html does not exist!` because relative path in `<link rel="import" href="../components/my-component.html">` is checked from `build\frontend\templates\` when it should be `build\frontend\templates\views`.

**To Reproduce**
1. Create two folders in `webapp\templates` and add a html file in each folder.
2. Add an import from one of them to the other.
3. Run `gradle vaadinAssembleClient`

**Expected behavior**
Relative paths between templates should work.

**Additional context**
The code that fails in [TranspileDependenciesTask.groovy](https://github.com/devsoap/gradle-vaadin-flow/blob/master/src/main/groovy/com/devsoap/vaadinflow/tasks/TranspileDependenciesTask.groovy#L189) results in the following output.
```
String htmlImports = """
    <link rel="import" href="../bower_components/polymer/polymer-element.html">
    <link rel="import" href="../components/my-component.html">
"""
htmlImports.findAll('.*rel="import".*href="(.*)".*').collect {
    java.util.regex.Matcher matcher = (it =~ /href=\"(.*)\"/)
    matcher ? matcher.group(1) : null
}.each { String importPath -> println importPath }

Output:
../bower_components/polymer/polymer-element.html
../components/my-component.html
```
A correct output could be:
```
../bower_components/polymer/polymer-element.html
./components/../components/my-component.html
```

**Comment by johndevs** [comment]
The relative paths should be relative to the ``frontend`` directory.

This means that if you have a templates in ``frontend/templates/root.html`` then the imports should look like this in that template:
```
<link rel="import" href="../bower_components/polymer/polymer-element.html">
<link rel="import" href="./components/my-component.html">
```

If you have a template in a sub-folder ``frontend/templates/views/view.html`` then the imports should look like this in that template:
```
<link rel="import" href="../../bower_components/polymer/polymer-element.html">
<link rel="import" href="../components/my-component.html">
```

So if you put the templates in a subfolder, then you need to adjust the relative paths so that they all lead up to the  ``frontend/templates`` . 

You're right now the validator seems to fail on those sub-folders which will need to be fixed.
