### ISSUE TITLE
jar task transpiles frontend code but doesn't add it to the jar

### ISSUE THREAD

**Issue by ssindelar** [devsoap/gradle-vaadin-flow#212]
**Desktop (please complete the following information):**
 - OS: Windows 10
 - JDK version: openjdk 11.0.1 2018-10-16
 - Gradle version: 5.1.1
 - Vaadin Plugin version: 1.0.0

**Describe the bug**
When production mode is enabled, building a jar of the project using the `jar`-task (not `bootJar` from the spring-boot plugin) transpiles the code but doesn't add it to the jar.

**To Reproduce**
1. Checkout https://github.com/devsoap/examples/tree/master/beverage-starter-flow-gradle
2. enable production mode in build.gradle
3. run `gradlew jar`
4. transpiled files are in build/webapp-gen but not in the jar file

**Expected behavior**
I would expect that the transpiled files added the to jar like it is with the `bootJar`-task or with the widgetset of the plugin for vaadin 7&8.

Thank you for your work.

**Comment by johndevs** [comment]
Adding the resources to the Jar would add redundant resources to a WAR  where both the JAR and the Webapp contents are added. 

For Spring Boot and BootJar it makes sense, since everything is bundled into the JAR.

If you want this behavior for the jar then you can add something like this to your build.gradle:
```groovy
 jar.dependsOn('vaadinAssembleClient')
 jar.from('build/webapp-gen')
 ...
```
List all the resource dirs you want to add to the Jar.
