### ISSUE TITLE
Lisence

### ISSUE THREAD

**Issue by alabotski** [devsoap/gradle-vaadin-flow#243]
I try to build a gradle project and constantly get a license error

The same project with maven builds and works fine.

 <a href='https://hostingkartinok.com/show-image.php?id=1c8515428d986e5721a7f9183df2ac61' title='flickr analog'><img src='https://s8.hostingkartinok.com/uploads/thumbs/2019/04/1c8515428d986e5721a7f9183df2ac61.png' alt='license.png' /></a>

More info
https://vaadin.com/forum/thread/17632445/license

**Comment by NotifierMan** [comment]
I had the same issue using `vaadin.autoconfigure()`. The problem is that `vaadin.autoconfigure()` adds `platform()` as a compile dependency.

> Platform contains everything, including commercial components sold by Vaadin Ltd. Platform also will include Core so you do not need to add it separately.

https://docs.devsoap.com/vaadin_flow_gradle_plugin_dependency_management/dependencies.html

To solve this I removed `vaadin.autoconfigure()` from the `build.gradle` and added the following dependencies:

```groovy
dependencies {
  compile vaadin.bom()
  compile vaadin.core()
  compile vaadin.materialTheme() // replace with "compile vaadin.lumoTheme()" if you want to use this one
  compile vaadin.dependency('icons:3.0.2')
}
```

**Comment by johndevs** [comment]
``autoconfigure()`` was changed to only add ``core()`` as a dependency in 1.3. 

Anyway, how you have done it is the correct way to do it manually :+1:
